config/routes.rb
Wohnungssucherportal::Application.routes.draw do

  devise_for :users

  resources :favorite_places

  get "visits/index"

  resources :flats do
    get 'all', 'prefill_url_form', :on => :collection
  end

  resource :visits
  
  root :to => 'flats#index'
  

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  
  include Flat::Options
  
  validates_presence_of :price, :available_on, :priority, :user_id, :city
  validates_numericality_of :square_meters, :price
  validates_length_of :subtitle, :maximum => 100
  
  # try preventing duplicates by only allowing one flat with same size and price per street
  validates_uniqueness_of :street, :scope => [:square_meters, :price], 
    :message => "There's already a flat in this street with same size and price."
  
  validate :available_until_must_be_after_available_on
  validates_inclusion_of :state, :in => STATES, :allow_nil => true

  # too lazy to fix this now
  #before_save :change_state!
  
  scope :for_index, :conditions => [
    # created_at is to exclude legacy flats, can be removed when user accounts are added and associated with flats
    "state NOT IN('i_rejected', 'not_available') AND created_at >= '2011-01-01'"
  ]
  
  scope :ordered, lambda { |*order|
    { :order => order.flatten.first || "state, created_at DESC" }
  }

  scope :have_visits, where(['visit_at IS NOT NULL']).order('visit_at DESC')
  
  belongs_to :user
  
  # FIXME it would be better to stub the request and have it run, than to prevent it completely
  acts_as_gmappable(:process_geocoding => !Rails.env.test?, :check_process => false)
  
  def square_meter_price
    ((price / square_meters.to_f) * 100).round / 100.to_f
  end
  
  def full_address
    city_with_postal = postal_code ? "#{postal_code} #{city}" : city
    [street, city_with_postal, country].join(", ")
  end
  alias :gmaps4rails_address :full_address
  
  def available_months
    return unless available_until
    ((available_until - available_on).to_i) / 30
  end
  
  # flats can be entered manually or be created from a scraped url
  def scraped?
    !url.blank?
  end
  
  def visit_passed?
    visit_at < Time.now
  end
  
  class << self
    
    def from_url(url)
      attributes = PageScraper.scrape(url).attributes
      Flat.new(attributes.merge(:url => url))
    end

    private
    
      def decode_html_entities(string)
        require 'htmlentities'
        HTMLEntities.new.decode(string)
      end
    
  end
  
  private 
  
    def available_until_must_be_after_available_on
      return true unless available_until
      if ((available_until - available_on).to_i) <= 1
        errors.add(:base, 'Avail until must be after avail on.')
      end
    end

    # if behaviour on state changes gets more complex, add a state machine.
    #def change_state!
    #  if visit_at_changed? && visit_at.present?
    #    self.state = "visit_scheduled" 
    #  end
    #end

end

app/models/flat/options.rb
# -*- coding: utf-8 -*-
module Flat::Options
  STATES = %w(
    new
    contact
    contacted
    contacted_2nd_time
    want_to_visit
    visit_scheduled
    visited
    i_rejected
    not_available
  )
  
  # should this be in the model?
  # TODO put his into user preferences?
  SORT_OPTIONS = [
    ['added on', 'created_at DESC'],
    ['available on', 'available_on ASC'],
    ['cost', 'price/square_meters DESC'],
    ['m²', 'square_meters DESC'],
    ['price', 'price DESC'],
    ['priority', 'priority ASC'],
    ['city', 'city ASC'],
  ]
  
  DEFAULT_PRIORITY = 2
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  rescue_from 'ActiveRecord::RecordNotFound' do
    redirect_to flats_path, :alert => "The requested flat could not be found."
  end
  
  def index
    session[:page]  = params[:page]  || session[:page]  || 1
    session[:order] = params[:order] || session[:order] || "state, created_at DESC"
    @flats = FlatDecorator.decorate(current_user.flats.for_index.ordered(session[:order]).page(session[:page]))
  end
  
  def all
    @flats = FlatDecorator.decorate(current_user.flats.all)
    render :action => 'index'
  end

  def show
    @flat = FlatDecorator.decorate(current_user.flats.find(params[:id]))
  end

  def prefill_url_form
  end
  
  def new
    if !params[:url].blank?
      @flat = Flat.from_url(params[:url])
    else
      @flat = Flat.new(:available_on => Date.today.next_month.at_beginning_of_month)
    end
    @flat.priority = Flat::DEFAULT_PRIORITY
    @flat.state    = Flat::STATES.first
  end

  def edit
    @flat = FlatDecorator.decorate(current_user.flats.find(params[:id]))
  end

  def create
    @flat = current_user.flats.new(params[:flat])

    if @flat.save
      flash[:created_flat_id] = @flat.id
      redirect_to flats_path, :notice => 'Flat created.'
    else
      flash[:error] = @flat.errors
      render :action => "new"
    end
  end

  def update
    @flat = current_user.flats.find(params[:id])

    respond_to do |format|
      if @flat.update_attributes(params[:flat])
        flash[:notice] = 'Flat updated.'
        format.html { redirect_to(flats_path) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @flat.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @flat = current_user.flats.find(params[:id])
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to(flats_path) }
      format.xml  { head :ok }
    end
  end
end

app/views/flats/_filter.html.erb
<div>
<%= form_tag do %>
  max: 
  price
  <%= select_tag(:max_price, options_for_select((300..2000).step(100))) %>
  area
  <%= select_tag(:max_area,  options_for_select((40..200).step(10))) %>
  rooms
  <%= select_tag(:max_rooms, options_for_select((1..9))) %>
  <%= submit_tag("filter", :style => "width: 100px;") %>
<% end %>
</div>

app/views/flats/_flats_list.html.haml
#flats-list
  - Flat::STATES.each do |state|
    - flats = @flats.select { |flat| flat.state == state }
    - unless flats.empty?
      = render :partial => "flats_table", :locals => { :flats => flats, :show_phone => false }
  

app/views/flats/_flats_table.html.haml
%table.flats
  %tr
    %th.state
      %h2= flats.first.state.humanize
    %th URL
    %th €
    %th m²
    %th.rooms rooms
    %th.avail avail
    %th prio
    
  - flats.each do |flat|
    %tr{:class => (flash[:created_flat_id].to_i == flat.id) ? 'just-created' : nil}  
      %td.street
        .overflow
          = link_to(edit_flat_path(flat), :class => "street-name") do
            = h(flat.city_with_street)
            %small= flat.subtitle_with_contact

      %td= flat.url ? link_to('link', flat.url) : 'N/A'
      %td= flat.price
      %td= flat.square_meters
      %td= flat.rooms ? flat.rooms : 'WG'
      %td= flat.start_date_with_duration
      %td= flat.priority
    
      / FIXME
      /%td=raw flat.phone.blank? ? "<b style='color:#d00'><i>missing</i></b>" : flat.phone

app/views/flats/_form.html.erb
<%= f.error_messages %>

<fieldset id="process_data">
  <p>
  <label>Status</label><br />
  
  <% Flat::STATES.each do |state| %>
    <%= f.radio_button(:state, state) %> 
    <%= f.label :state, state.humanize, :value => state.humanize %><br />
  <% end %>
  </p>

  <p>
    <%= f.label :priority %>&nbsp;
    <% ['great', 'ok', 'so-so'].each_with_index do |text, i| %>
      <%= f.radio_button :priority, (i + 1) %>
      <%= f.label :priority, text, :value => (i + 1) %>
    <% end %>    
  </p>

  <p>
    <%= f.label :visit_at %><br />
    <%= f.text_field :visit_at, :value => (@flat.visit_at && l(@flat.visit_at, :format => :german)) %>
  </p>

  <p>
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </p>

  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit(@flat.new_record? ? 'Create' : 'Update') %>
  </p>

  
</fieldset>

<fieldset id="base_data">
  <h3>Flat Info</h3>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </p>
  <p>
    <%= f.label :neighbourhood %><br />
    <%= f.text_field :neighbourhood %>
  </p>
  <p>
    <%= f.label :rooms %><br />
    <%= f.text_field :rooms %>
  </p>
  <p>
    <%= f.label :square_meters %><br />
    <%= f.text_field :square_meters %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  
  <p>
    <%= f.label :available_from, "Availability" %><br />
    from: 
      <%= f.text_field :available_on, :value => l(@flat.available_on, :format => :german) %>
    &nbsp;until: 
      <%= f.text_field :available_until, :value => (@flat.available_until && l(@flat.available_until, :format => :german)) %>
  </p>
  
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </p>

  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>

  <p>
    <%= link_to("Open original ad", @flat.url , :target => '_blank') %>
  </p>
</fieldset>

app/views/flats/_map.html.erb
<div id="map">
  <script type="text/javascript">
    function initialize() {
      map = initMap(800, 600);
      // add marker and center map
      var geocoder = new GClientGeocoder();
      var addressString = '<%= flat.full_address %>';
      geocoder.getLatLng(addressString, function(latLng) {
        map.setCenter(latLng, 15);
        map.addOverlay(new GMarker(latLng, {'title': addressString }));          
      });
    }
    </script>
    
  <body onload="initialize()" onunload="GUnload()">
    <div id="map_canvas" style="width: 800px; height: 600px; border: 1px solid #000"></div>
</div>

app/views/flats/_one_flat_map.html.erb
<script type="text/javascript">
  function initialize() {
  
      // set up new map
      var mapOptions = {
          zoom: 13,
          mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
  
      var geocoder = new google.maps.Geocoder();
  
      centerMap(map, geocoder, '<%= "#{flat.street}, #{flat.city}" %>');
      placeMarkers(<%=raw current_user.favorite_places.to_json %>, 'green');
      placeMarkers([<%=raw flat.model.to_json %>], 'red');
  }
</script>
    
<div id="map_canvas"></div>

app/views/flats/_overview_map.html.erb
<script type="text/javascript">

function initialize() {
  
  // set up new map
  var mapOptions = {
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scaleControl: true
  };  
  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
  
  // initialize one infobox
  var infowindow = new google.maps.InfoWindow({
    	content: 'empty at the start'
    });		

  // set center
  var geocoder = new google.maps.Geocoder();

  centerMap(map, geocoder, <%=raw current_user.city.to_json %>);  
  
  // pass server data to js
  var favoritePlaces = <%=raw current_user.favorite_places.to_json %>;
  var addresses      = [<%=raw @flats.map(&:to_json).join(', ') %>];
  
  placeMarkers(favoritePlaces, 'green', infowindow);
  var flatMarkers = placeMarkers(addresses, 'red', infowindow);

  initMarkerHighlighting(flatMarkers);
}
</script>

<div id="map_canvas"></div>

app/views/flats/_sort_bar.html.haml
%div#sort-bar
  sort by: 
  %span#sort-options
    - Flat::SORT_OPTIONS.each do |name, value|
      = link_to_unless_current(name, flats_path(:order => value))
  |
  %i
    = "showing #{@flats.size} flats "
    =raw "(" + link_to("show all #{current_user.flats.count}", all_flats_path) + ")"
  | 
  = link_to('Sign out', destroy_user_session_path, :method => :delete, :class => 'sign-out')
  | 
  = link_to('Edit', edit_user_registration_path)
  
  = render :partial => "filter"

app/views/flats/edit.html.erb
<% @initialize = true %>

<div id="navigation">
<%= link_to 'Back to list', flats_path %> |
<%= link_to 'Show', @flat %> |
<%= link_to 'Destroy', @flat, :confirm => 'Are you sure?', :method => :delete %>
</div>

<div id="left_col">
  <div id="infos">
    
    <h1><%= @flat.full_address %></h1>
    
    <table id="flat-data">
    <% for name in @flat.attribute_names.sort.each %>
      <% if !(@flat[name].blank? || ["created_at", "gmaps", "id", "latitude", "longitude", "updated_at", "user_id"].include?(name)) %>
        <% if name == "url" %>
	  <tr>
            <th><%=       name  %></th>
            <td><%= link_to('link', @flat.url) %></td>
	  </tr>
        <% else %>
	  <tr>
            <th><%=       name  %></th>
            <td><%= @flat[name] %></td>
	  </tr>
        <% end %>
      <% end %>
    <% end %>
    </table>
    
  </div>

<h1>Editing flat</h1>

<%= form_for(@flat) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

</div>

<%= render :partial => 'one_flat_map', :locals => { :flat => @flat } %>

app/views/flats/index.html.erb
<% @initialize = true %>

<%= render :partial => 'overview_map', :locals => { :flats => @flats } %>

<%= link_to 'Add flat', '/flats/prefill_url_form' %> | 
<%= link_to 'Visits', visits_path %> | 
<%= link_to 'Edit favorite places', favorite_places_path %> | 
<% if controller.action_name == 'index' %>
<%= paginate @flats %>
<% end %>


<h1 style="display: none;">Flats</h1>

<%= render :partial => 'flats_list' %>
<%= render :partial => 'sort_bar' %>

app/views/flats/new.html.erb
<%= link_to 'Cancel and back to list', flats_path %>

<h1>Create Wohnung</h1>

<%= form_for(@flat) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/flats/prefill_url_form.html.erb
<%= link_to 'Back', flats_path %>

<h1>New flat</h1>

<p>
  <%= error_messages_for 'flat' %>
</p>

<%= form_tag({:action => 'new'}, :method => :get) do %>
  <p>
    <%= label_tag :url, "URL for prefilling the form (optional):" %><br />
    <%= text_field_tag :url, {}, { :style => 'width: 800px'} %>
  </p>
  
  <p>
    <%= submit_tag 'Continue' %>
  </p>
<% end %>

app/views/flats/show.html.erb
<% @initialize = true %>

<div id="navigation">
  <%= link_to 'Back to list', flats_path %> |
  <%= link_to 'Edit', edit_flat_path(@flat) %> |
  <%= link_to 'Destroy', @flat, :confirm => 'Are you sure?', :method => :delete %>
</div>

<div id="left_col">
  <div id="infos">
    
    <h2><%= @flat.street %></h2>
    
    <table id="flat-data">
      <thead>
      <tr>
        <th>neighbourhood</th>
        <td><%= @flat.neighbourhood %></td>
      </tr>
      <% if @flat.rooms %>
      <tr>
        <th>number of rooms</th>
        <td><%= @flat.rooms %></td>
      </tr>
      <% end %>
      <tr>
        <th>size</th>
        <td><%= @flat.square_meters %>m²</td>
      </tr>
      <tr id="separator">
        <th>price</th>
        <td>€<%= @flat.price %></td>
      </tr>
      </thead>
      <tr>
        <th>in state</th>
        <td><%= @flat.state.humanize %></td>
      </tr>
      <tr>
        <th>availability</th>
        <td><%= @flat.availability %>
        </td>
      </tr>
      <tr>
        <th>contact</th>
        <td><%=raw @flat.contact %></td>
      </tr>
      <tr>
        <th>visit at</th>
        <td><%=raw @flat.visit_at %>
        </td>
      </tr>
      <tr>
        <th>priority</th>
        <td><%= @flat.priority %></td>
      </tr>
      <tr>
        <td colspan="2"><%= link_to('read original ad', @flat.url, :target => '_blank') %></td>
      </tr>
      <tr>
        <th colspan="2">comments:</th>
      </tr>
      <tr>
        <td colspan="2"><%=raw @flat.comment %></th>
      </tr>
    </table>
    
  </div>
</div>

<%= render :partial => 'one_flat_map', :locals => { :flat => @flat } %>