config/routes.rb
Wohnungssucherportal::Application.routes.draw do

  devise_for :users

  resources :favorite_places

  get "visits/index"

  resources :flats do
    get 'all', 'prefill_url_form', :on => :collection
  end

  resource :visits
  
  root :to => 'flats#index'
  

end

app/models/favorite_place.rb
class FavoritePlace < ActiveRecord::Base

  validates_presence_of :street, :city
  belongs_to :user
  
  # FIXME it would be better to stub the request and have it run, than to prevent it completely
  acts_as_gmappable(:process_geocoding => !Rails.env.test?)

  def full_address
    [street, city, country].join(", ")
  end
  alias :gmaps4rails_address :full_address
  
end

app/controllers/favorite_places_controller.rb
class FavoritePlacesController < ApplicationController
  # GET /favorite_places
  # GET /favorite_places.json
  def index
    @favorite_places = current_user.favorite_places

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @favorite_places }
    end
  end

  # GET /favorite_places/1
  # GET /favorite_places/1.json
  def show
    @favorite_place = current_user.favorite_places.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @favorite_place }
    end
  end

  # GET /favorite_places/new
  # GET /favorite_places/new.json
  def new
    @favorite_place = current_user.favorite_places.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @favorite_place }
    end
  end

  # GET /favorite_places/1/edit
  def edit
    @favorite_place = current_user.favorite_places.find(params[:id])
  end

  # POST /favorite_places
  # POST /favorite_places.json
  def create
    @favorite_place = current_user.favorite_places.new(params[:favorite_place])

    respond_to do |format|
      if @favorite_place.save
        format.html { redirect_to @favorite_place, :notice => 'Favorite place was successfully created.' }
        format.json { render :json => @favorite_place, :status => :created, :location => @favorite_place }
      else
        format.html { render :action => "new" }
        format.json { render :json => @favorite_place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorite_places/1
  # PUT /favorite_places/1.json
  def update
    @favorite_place = current_user.favorite_places.find(params[:id])

    respond_to do |format|
      if @favorite_place.update_attributes(params[:favorite_place])
        format.html { redirect_to @favorite_place, :notice => 'Favorite place was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @favorite_place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_places/1
  # DELETE /favorite_places/1.json
  def destroy
    @favorite_place = current_user.favorite_places.find(params[:id])
    @favorite_place.destroy

    respond_to do |format|
      format.html { redirect_to favorite_places_url }
      format.json { head :ok }
    end
  end
end

app/views/favorite_places/_form.html.erb
<%= form_for(@favorite_place) do |f| %>
  <% if @favorite_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_place.errors.count, "error") %> prohibited this favorite_place from being saved:</h2>

      <ul>
      <% @favorite_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorite_places/edit.html.erb
<h1>Edit favorite place</h1>

<%= render 'form' %>

<p>
<%= link_to 'Back', favorite_places_path %>
</p>

app/views/favorite_places/index.html.erb
<%= link_to 'Back to list', root_path %>

<h1>Favorite places</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>City</th>
    <th></th>
    <th></th>
  </tr>

<% @favorite_places.each do |favorite_place| %>
  <tr>
    <td><%= favorite_place.name %></td>
    <td><%= favorite_place.street %></td>
    <td><%= favorite_place.city %></td>
    <td><%= link_to 'Edit', edit_favorite_place_path(favorite_place) %></td>
    <td><%= link_to 'Destroy', favorite_place, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite place', new_favorite_place_path %>

app/views/favorite_places/new.html.erb
<h1>New favorite place</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_places_path %>

app/views/favorite_places/show.html.erb
<p>
  <b>Name:</b>
  <%= @favorite_place.name %>
</p>

<p>
  <b>Street:</b>
  <%= @favorite_place.street %>
</p>

<p>
  <b>City:</b>
  <%= @favorite_place.city %>
</p>


<%= link_to 'Edit', edit_favorite_place_path(@favorite_place) %> |
<%= link_to 'Back', favorite_places_path %>